kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'jmvillamil@cysce.com'
      smtp_auth_username: 'jmvillamil@cysce.com'
      smtp_auth_password: 'xxxx'
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      group_by: ['alertname', 'priority']
      group_wait: 10s
      group_interval: 60s
      repeat_interval: 60s
      receiver: 'alert-emailer'
    receivers:
    - name: alert-emailer
      email_configs:
      - to: 'jmvillamil@gmail.com'
        from: 'jmvillamil@cysce.com'
        smarthost: smtp.gmail.com:587
        auth_username: 'jmvillamil@cysce.com'
        auth_identity: 'jmvillamil@cysce.com'
        auth_password: 'xxxx'