version: '3.9'

networks:
  cysdvps:
    driver: bridge

services:

  postgres:
    image: <nexus>/postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloakdb
      POSTGRES_USER: admindb
      POSTGRES_PASSWORD: Passw0rd
    networks:
      - cysdvps
    volumes:
      - postgres-data:/var/lib/postgresql/data

  keycloak:
    depends_on:
      - postgres
    container_name: local_keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: passw0rd
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloakdb
      DB_USER: admindb
      DB_PASSWORD: Passw0rd
    image: <nexus>/jboss/keycloak:16.1.0
    ports:
      - "8080:8080"
      - "9990:9990"
    restart: unless-stopped
    networks:
      - cysdvps
volumes:
    postgres-data:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: <path>