version: '3.9'

networks:
  cysdvps:
    driver: bridge

services:

  postgres:
    image: postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
    networks:
      - cysdvps
    volumes:
      - postgres-data:/var/lib/postgresql/data

  keycloak:
    depends_on:
      - postgres
    container_name: local_keycloak
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_ADMIN}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASS}      
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: ${POSTGRESQL_DB}
      DB_USER: ${POSTGRESQL_USER}
      DB_PASSWORD: ${POSTGRESQL_PASS}
    image: jboss/keycloak:${KEYCLOAK_VERSION}
    ports:
      - "8080:8080"
      - "9990:9990"
    restart: unless-stopped
    networks:
      - cysdvps
volumes:
    postgres-data:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/Volumes/DATA/CYSCE/INTEGRO/volumen/postgresql/data'