{
 "title": "LOGS - LOKI",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "GROUP", "query": "label_names()" },
   { "name": "ITEM", "query": "label_values($GROUP)" },
   { "name": "OP", "query": "|=,!=,|~,!~," },
   { "name": "STRING" }
  ]
 },
 "panels": [
  { "title": "Filter by String", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "COMPONENT" },
  {
   "title": "LOGS - STRING:\"$STRING\"",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{$GROUP=\"$ITEM\"}$OP\"$STRING\""
    }
   ]
  },
  {
   "title": "Logs por hora",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "rate({$GROUP=\"$ITEM\"}$OP\"$STRING\"[1h])  "
    }
   ]
  },
  { "title": "Machine monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Cluster memory usage : cys-master-01",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^cys-master-01\"})/ sum (machine_memory_bytes{kubernetes_io_hostname=~\"^cys-master-01\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster memory usage : cys-woker-03",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^cys-worker-03\"})/ sum (machine_memory_bytes{kubernetes_io_hostname=~\"^cys-worker-03\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster memory usage : cys-worker-04",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^cys-worker-04\"})/ sum (machine_memory_bytes{kubernetes_io_hostname=~\"^cys-worker-04\"}) * 100"
    }
   ]
  },
  {
   "title": "Used : cys-master-01",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^cys-master-01\"})"
    }
   ]
  },
  {
   "title": "Total : cys-master-01",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^cys-master-01\"})"
    }
   ]
  },
  {
   "title": "Used : cys-worker-03",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^cys-worker-03\"})"
    }
   ]
  },
  {
   "title": "Total : cys-worker-03",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^cys-worker-03\"})"
    }
   ]
  },
  {
   "title": "Used : cys-worker-04",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^cys-worker-04\"})"
    }
   ]
  },
  {
   "title": "Total : cys-worker-04",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^cys-worker-04\"})"
    }
   ]
  }
 ]
}