apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockapp
  namespace: mockapp
  labels:
    app: mockapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mockapp
  template:
    metadata:
      labels:
        app: mockapp
    spec:
      containers:
        - name: mockapp
          image: nexus/mockapp:latest
          ports:
            - name: mockapp
              containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mockapp
  name: mockapp
  namespace: mockapp
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 31755
  selector:
    app: mockapp
  sessionAffinity: None
  type: NodePort