apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockapp
  namespace: default
spec:
  template:
    spec:
      containers:
        name: mockapp
        image: nuxus/mockapp:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP