apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  namespace: kube-system
spec:
  selector: 
    app.kubernetes.io/name: kube-state-metrics
  type: NodePort  
  ports:
    - port: 8080
      name: http-metrics
      targetPort: 8080
      nodePort: 31890
    - port: 8081
      name: telemetry
      targetPort: 8081
      nodePort: 31891