curl -LO https://raw.githubusercontent.com/villajuancho/httpserver/main/nginx/public/k8s/config/calico.tar
curl -LO https://raw.githubusercontent.com/villajuancho/httpserver/main/nginx/public/k8s/config/grafana.tar
curl -LO https://raw.githubusercontent.com/villajuancho/httpserver/main/nginx/public/k8s/config/k8s.tar
curl -LO https://raw.githubusercontent.com/villajuancho/httpserver/main/nginx/public/k8s/config/keycloak.tar
curl -LO https://raw.githubusercontent.com/villajuancho/httpserver/main/nginx/public/k8s/config/keycloak-docker.tar
curl -LO https://raw.githubusercontent.com/villajuancho/httpserver/main/nginx/public/k8s/config/kong.tar
curl -LO https://raw.githubusercontent.com/villajuancho/httpserver/main/nginx/public/k8s/config/prometheus.tar
curl -LO https://raw.githubusercontent.com/villajuancho/httpserver/main/nginx/public/k8s/config/kongoidc.tar
curl -LO https://raw.githubusercontent.com/villajuancho/httpserver/main/nginx/public/k8s/config/longhorn.tar
curl -LO https://raw.githubusercontent.com/villajuancho/httpserver/main/nginx/public/k8s/config/metrics.tar
curl -LO https://raw.githubusercontent.com/villajuancho/httpserver/main/nginx/public/k8s/config/logging.tar
curl -LO https://raw.githubusercontent.com/villajuancho/httpserver/main/nginx/public/k8s/config/config.yaml
