version: "3.9"
networks:
  cysnexus:
    driver: bridge
services:
  nexus:
    image: "sonatype/nexus3:3.38.1"
    restart: unless-stopped
    networks:
      - cysnexus
    ports:
      - "8099:8081"
      - "5000:5000"
      - "5001:5001"
      - "5002:5002"
    volumes:
      - /home/ubuntu/nexus/nexus-data:/nexus-data
      - /home/ubuntu/nexus/nexus-public/install:/opt/sonatype/nexus/public/install