global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
  - /etc/prometheus2/alert.rules
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  - job_name: 'k8s-kong'
    static_configs:
      - targets: ['192.168.88.72:9100','192.168.88.70:9100']

