apiVersion: v1
kind: Service
metadata:
  name: kong-database
  namespace: kong-namespace
spec:
  selector:
    app: kong-database
  ports:
    - port: 5432
      targetPort: 5432
---
# PostgreSQL StatefulSet - ConfigMap
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kong-database
  namespace: kong-namespace
spec:
  selector:
    matchLabels:
      app: kong-database
  serviceName: kong-database
  replicas: 1
  template:
    metadata:
      labels:
        app: kong-database
    spec:
      containers:
      - name: kong-database
        image: nexus/postgres:9.6
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: kong-db-disk
          mountPath: /data
          subPath: pgdata
        env:
        - name: "POSTGRES_USER"
          value: "kong"
        - name: "POSTGRES_DB"
          value: "kong"
        - name: "POSTGRES_PASSWORD"
          value: "kongpass"
        - name: "PGDATA"
          value: "/data/pgdata"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: selectkey
                operator: In
                values:
                - selectvalue
      volumes:
        - name: kong-db-disk
          persistentVolumeClaim:
            claimName: kong-db-pvc