apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: konga-data-pvc
  namespace: kong-namespace
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi