apiVersion: v1
kind: Pod
metadata:
  name: prepare-kong
  namespace: kong-namespace
  labels:
    app: prepare-kong
spec:
  containers:
  - name: prepare-kong
    imagePullPolicy: IfNotPresent
    image: nexus/kongoidc:latest
    command: ["sleep","3h"]
    env:
    - name: "KONG_DATABASE"
      value: "postgres"
    - name: KONG_PG_HOST
      value: "kong-database"
    - name: KONG_PG_PASSWORD
      value: "kongpass"