apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak-namespace
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: nexus/jboss/keycloak:16.1.0
        ports:
          - name: jgroups
            containerPort: 7600
          - name: http
            containerPort: 8080
          - name: https
            containerPort: 8443
        env:
        - name: KEYCLOAK_USER
          value: "admin"
        - name: KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: password
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: DB_ADDR
          value: keycloak-psql
        - name: DB_DATABASE
          value: postgres
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-psql
              key: password
        - name: DB_SCHEMA
          value: public
        - name: DB_VENDOR
          value: POSTGRES
        - name: JGROUPS_DISCOVERY_PROTOCOL
          value: dns.DNS_PING
        - name: JGROUPS_DISCOVERY_PROPERTIES
          value: "dns_query=keycloak"
        - name: CACHE_OWNERS_COUNT
          value: "2"
        - name: CACHE_OWNERS_AUTH_SESSIONS_COUNT
          value: "2"
        volumeMounts:
        - name: theme
          mountPath: /opt/jboss/keycloak/themes
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: selectkey
                operator: In
                values:
                - 'selectvalue'
      volumes:
      - name: theme
        persistentVolumeClaim:
          claimName: keycloak-pvc