apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: keycloak-namespace
  labels:
    service: keycloak
spec:
  type: NodePort
  ports:
  - port: 8080
    name: http
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
  - port: 8443
    name: https
    targetPort: 8443
    nodePort: 30043
    protocol: TCP
  selector:
    app: keycloak
