apiVersion: v1
kind: Service
metadata:
  name: grafana-loki
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '3100'
spec:
  selector: 
    app: grafana-loki
  type: NodePort  
  ports:
    - port: 3100
      targetPort: 3100
      nodePort: 32100