apiVersion: v1
kind: Service
metadata:
  name: kong-konga
  namespace: kong-namespace
  labels:
    service: kong-konga
spec:
  selector:
    app: kong-konga
  type: NodePort
  ports:
  - port: 1337
    name: web
    targetPort: 1337
    nodePort: 30001
    protocol: TCP